<?php

namespace Dkedzia\EnvGenerator\Template;

class LaravelTemplate extends EnvTemplateBase
{
    public const APP_NAME = 'APP_NAME';
    public const APP_ENV = 'APP_ENV';
    public const APP_KEY = 'APP_KEY';
    public const APP_DEBUG = 'APP_DEBUG';
    public const APP_URL = 'APP_URL';
    public const LOG_CHANNEL = 'LOG_CHANNEL';
    public const LOG_DEPRECATIONS_CHANNEL = 'LOG_DEPRECATIONS_CHANNEL';
    public const LOG_LEVEL = 'LOG_LEVEL';
    public const DB_CONNECTION = 'DB_CONNECTION';
    public const DB_HOST = 'DB_HOST';
    public const DB_PORT = 'DB_PORT';
    public const DB_DATABASE = 'DB_DATABASE';
    public const DB_USERNAME = 'DB_USERNAME';
    public const DB_PASSWORD = 'DB_PASSWORD';
    public const BROADCAST_DRIVER = 'BROADCAST_DRIVER';
    public const CACHE_DRIVER = 'CACHE_DRIVER';
    public const FILESYSTEM_DISK = 'FILESYSTEM_DISK';
    public const QUEUE_CONNECTION = 'QUEUE_CONNECTION';
    public const SESSION_DRIVER = 'SESSION_DRIVER';
    public const SESSION_LIFETIME = 'SESSION_LIFETIME';
    public const MEMCACHED_HOST = 'MEMCACHED_HOST';
    public const REDIS_HOST = 'REDIS_HOST';
    public const REDIS_PASSWORD = 'REDIS_PASSWORD';
    public const REDIS_PORT = 'REDIS_PORT';
    public const MAIL_MAILER = 'MAIL_MAILER';
    public const MAIL_HOST = 'MAIL_HOST';
    public const MAIL_PORT = 'MAIL_PORT';
    public const MAIL_USERNAME = 'MAIL_USERNAME';
    public const MAIL_PASSWORD = 'MAIL_PASSWORD';
    public const MAIL_ENCRYPTION = 'MAIL_ENCRYPTION';
    public const MAIL_FROM_ADDRESS = 'MAIL_FROM_ADDRESS';
    public const MAIL_FROM_NAME = 'MAIL_FROM_NAME';
    public const AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID';
    public const AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY';
    public const AWS_DEFAULT_REGION = 'AWS_DEFAULT_REGION';
    public const AWS_BUCKET = 'AWS_BUCKET';
    public const AWS_USE_PATH_STYLE_ENDPOINT = 'AWS_USE_PATH_STYLE_ENDPOINT';
    public const PUSHER_APP_ID = 'PUSHER_APP_ID';
    public const PUSHER_APP_KEY = 'PUSHER_APP_KEY';
    public const PUSHER_APP_SECRET = 'PUSHER_APP_SECRET';
    public const PUSHER_HOST = 'PUSHER_HOST';
    public const PUSHER_PORT = 'PUSHER_PORT';
    public const PUSHER_SCHEME = 'PUSHER_SCHEME';
    public const PUSHER_APP_CLUSTER = 'PUSHER_APP_CLUSTER';
    public const VITE_PUSHER_APP_KEY = 'VITE_PUSHER_APP_KEY';
    public const VITE_PUSHER_HOST = 'VITE_PUSHER_HOST';
    public const VITE_PUSHER_PORT = 'VITE_PUSHER_PORT';
    public const VITE_PUSHER_SCHEME = 'VITE_PUSHER_SCHEME';
    public const VITE_PUSHER_APP_CLUSTER = 'VITE_PUSHER_APP_CLUSTER';

    protected array $variables = [
        self::APP_NAME => '',
        self::APP_ENV => '',
        self::APP_KEY => '',
        self::APP_DEBUG => 'true',
        self::APP_URL => 'http://localhost',
        self::LOG_CHANNEL => 'stack',
        self::LOG_DEPRECATIONS_CHANNEL => 'null',
        self::LOG_LEVEL => 'debug',
        self::DB_CONNECTION => 'mysql',
        self::DB_HOST => 'db',
        self::DB_PORT => '3306',
        self::DB_DATABASE => 'booking_api',
        self::DB_USERNAME => 'root',
        self::DB_PASSWORD => 'root',
        self::BROADCAST_DRIVER => 'log',
        self::CACHE_DRIVER => 'file',
        self::FILESYSTEM_DISK => 'local',
        self::QUEUE_CONNECTION => 'sync',
        self::SESSION_DRIVER => 'file',
        self::SESSION_LIFETIME => '120',
        self::MEMCACHED_HOST => '127.0.0.1',
        self::REDIS_HOST => '127.0.0.1',
        self::REDIS_PASSWORD => 'null',
        self::REDIS_PORT => '6379',
        self::MAIL_MAILER => 'smtp',
        self::MAIL_HOST => 'mailhog',
        self::MAIL_PORT => '1025',
        self::MAIL_USERNAME => 'null',
        self::MAIL_PASSWORD => 'null',
        self::MAIL_ENCRYPTION => 'null',
        self::MAIL_FROM_ADDRESS => '"hello@example.com"',
        self::MAIL_FROM_NAME => '"${APP_NAME}"',
        self::AWS_ACCESS_KEY_ID => '',
        self::AWS_SECRET_ACCESS_KEY => '',
        self::AWS_DEFAULT_REGION => 'us-east-1',
        self::AWS_BUCKET => '',
        self::AWS_USE_PATH_STYLE_ENDPOINT => 'false',
        self::PUSHER_APP_ID => '',
        self::PUSHER_APP_KEY => '',
        self::PUSHER_APP_SECRET => '',
        self::PUSHER_HOST => '',
        self::PUSHER_PORT => '443',
        self::PUSHER_SCHEME => 'https',
        self::PUSHER_APP_CLUSTER => 'mt1',
        self::VITE_PUSHER_APP_KEY => '"${PUSHER_APP_KEY}"',
        self::VITE_PUSHER_HOST => '"${PUSHER_HOST}"',
        self::VITE_PUSHER_PORT => '"${PUSHER_PORT}"',
        self::VITE_PUSHER_SCHEME => '"${PUSHER_SCHEME}"',
        self::VITE_PUSHER_APP_CLUSTER => '"${PUSHER_APP_CLUSTER}"',
    ];
}